### ISSUE TITLE
faas-cli push made it so that I couldn't update my container

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#114]
I am working on the [faas-and-furious/youtube-dl](https://github.com/faas-and-furious/youtube-dl) function. My workflow was:

1. Push docker [image to docker hub](https://hub.docker.com/r/ems5311/youtube-dl/) with `faas-cli push -f <yaml>`
2. Update function `entry.sh` file
3. Retry `faas-cli build -f <yaml>; faas-cli deploy -f <yaml>`, and the function is not updated!

My current version of the code: https://github.com/faas-and-furious/youtube-dl

The only way I can get my image to reflect the new state of the `youtube-dl` function is to name the image something different in the YAML file.

I tried build with `--no-cache` and it doesn't work either.

Also, If I do `faas-cli push -f <YAML>`, it will show `Layer already exists` for every line.

The yaml file is:
```
provider:
  name: faas
  gateway: http://localhost:8080

functions:
  youtube-dl:
    lang: Dockerfile
    handler: ./youtube-dl
    image: ems5311/youtube-dl:latest
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:
