### ISSUE TITLE
Proposal: Support port mapping

### ISSUE THREAD

**Issue by austinfrey** [openfaas/faas-cli#131]
## Expected Behaviour

Map ports via a command line `-p` flag or using the `stack.yml` file similar to `docker-compose.yml`
```
functions:
    echoit:
        ...
        ports:
            - 9222:9222
````

## Current Behaviour

Currently you need to add a function to a `docker-compose.yml` file and deploy with the rest of the OpenFaaS framework or deploy using the Docker CLI.

## Context

The current use would be to more easily allow debugging by exposing another port and being able to attach debugging tools, but there certainly are other use cases where port mapping might be useful.

Pros:
easier debugging workflow

Cons:
possibly security?
