### ISSUE TITLE
faas-cli when used with stack.yml should pick up secrets

### ISSUE THREAD

**Issue by ericstoekl** [openfaas/faas-cli#227]
Secrets could be put into a stack.yml file like so:

```
provider:
  name: faas
  gateway: http://localhost:8080

functions:
  secrettest:
    lang: node
    handler: ./secrettest
    image: ems5311/secrettest:0.1
    secrets:
      - db-user-pass
```

Currently, the secret list in this situation would not be picked up by `faas-cli`

## Expected Behaviour

Secrets can be applied via the stack.yml file.

## Current Behaviour

Secrets must be set via the `--secrets` command line parameter.

## Possible Solution

https://github.com/ericstoekl/faas-cli/commit/97110be8511b1f2fba699398d4ede7cbff82ee14

## Steps to Reproduce (for bugs)

1. Add a `secrets:` object to a function in the stack yaml
2. `faas-cli deploy`
3. Observe that the secret was not picked up
4.

## Context

While testing secrets proposed change:
https://github.com/openfaas/faas-netes/pull/86#issuecomment-345498646

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker version 17.11.0-ce-rc2, build d7062e5
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
kubernete 1.8.3 via minikube
* Operating System and version (e.g. Linux, Windows, MacOS):
ubuntu 1604
* Link to your project or a code example to reproduce issue:
