### ISSUE TITLE
Help wanted: `faas new` to take --prefix for username/repo

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#338]
With tutorials on `faas new` I often have to tell people to edit their YAML file and introduce a prefix with their username or alternative Docker registry. We need a flag for this

## Expected Behaviour

`faas new --lang node jsrocks --prefix alexellis`

`faas new --lang node jsrocks -p 10.0.95.1:5000`

This should then reflect in the YAML file generated with the function:

```
provider:
  name: faas
  gateway: http://localhost:8080

functions:
  jsrocks:
    lang: node
    handler: ./jsrocks
    image: alexellis/jsrocks
```

## Current Behaviour

I ask people to edit their YAML file after generating a function changing `image: jsrocks` to `image: alexellis/jsrocks` etc.

## Code

Cobra command:

https://github.com/openfaas/faas-cli/blob/master/commands/new_function.go#L24

Templating line for the YAML file:

https://github.com/openfaas/faas-cli/blob/master/commands/new_function.go#L135
