### ISSUE TITLE
Suggestion: block appending of the same function more than once

### ISSUE THREAD

**Issue by samueleaton** [openfaas/faas-cli#354]
Summary: Using "append" with the "new" command allows duplicate function names

Using the `--append` option appends function to yaml file regardless of if the function name is already taken, creating ambiguous yaml file.

## Expected Behaviour
It should return an error if the function name would result in a duplicate.

## Current Behaviour
it will continue to append.

Example when running `faas-cli new yee --lang ruby -f functions.yml` more than once.

```yml
functions:
  yee:
    lang: ruby
    handler: ./yee
    image: yee
  yee:
    lang: ruby
    handler: ./yee
    image: yee
```

## Your Environment
- Docker `17.12.0-ce`
- Using Docker Swarm
- MacOS
