### ISSUE TITLE
Question on self-signed SSL certs

### ISSUE THREAD

**Issue by Lawouach** [openfaas/faas-cli#376]
Hi all,

I have deployed OpenFaaS on a cluster and made the gateway accessible via an Ingress that accepts both HTTP and HTTPS. The latter is using a self-signed cert as this is a demo only cluster.

When I try to deploy, I'm getting:

```
$ export gw=http://demo.foo.bar
$ faas-cli deploy -f astre.yml --gateway $gw
Deploying: astre.

Is FaaS deployed? Do you need to specify the --gateway flag?
Put https://demo.foo.bar/system/functions: x509: certificate signed by unknown authority
```

With the config as follows:

```yaml
provider:
  name: faas
  gateway: http://demo.foo.bar

functions:
  astre:
    lang: python3-flask
    handler: ./astre
    image: astre
```

I don't see a flag telling faas-cli to accept insecure connections.

I could also try to reconfigure my ingress to not redirect to HTTPS I guess.

Is there a way to support insecure connections? Much like the `-k` flag in curl :)

Thanks,
