### ISSUE TITLE
Feature: Generate Kubernetes CRD YAML files via cli

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#426]
The new definition for the Kubernetes CRD used in OpenFaaS Operator is different from the current stack file YAML definition.

I think the faas-cli should be used to generate/build/test functions in the stack.yml format and then if deployment is needed via `kubectl` then we should add a command to generate OpenFaaS Operator YAML. 

## Example conversion

stack.yml

```yaml
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  nodeinfo:
    lang: node
    handler: ./nodeinfo
    image: nodeinfo
```

The Kubernetes YAML omits any build-context such as the language or the `handler` folder, but will keep anything such as the environment, labels and etc.

Generates this:

```yaml
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: nodeinfo
  namespace: openfaas-fn
spec:
  name: nodeinfo
  image: functions/nodeinfo
  environment:
    write_debug: "true"
```

## Workflow

* Create two functions

```
faas-cli new --lang python fn-1 --username=alexellis2
faas-cli new --apend=./fn-1.yml --lang python fn-2  --username=alexellis2
```

* Build the functions and push them

```
faas-cli build -f fn-1.yml
faas-cli push -f fn-1.yml
```

* Apply to Kubernetes

```
faas-cli generate --api=openfaas.com/v1alpha2 --yaml fn-1.yml | kubectl apply  -f
```

## Suggested CLI command:

```bash
faas-cli generate --api=openfaas.com/v1alpha2 -f stack.yml

# Pipe to kubectl:
faas-cli generate --api=openfaas.com/v1alpha2 --yaml stack.yml | kubectl apply  -f
```

This would go to stdout and could be piped into a yaml file for use with kubectl

Unsure on the wording for `generate`, but this should be a new sub-command.

cc @affix @johnmccabe @openfaas/kubernetes
