### ISSUE TITLE
Support annotations in function schema

### ISSUE THREAD

**Issue by ewilde** [openfaas/faas-cli#436]
Co-ordinating issue see: https://github.com/openfaas/faas/issues/682 

## Expected Behaviour
CLI should support the new `annotations` attribute

## Current Behaviour
n/a

## Possible Solution
```
provider:
  name: faas
  gateway: http://127.0.0.1:8080  # can be a remote server

  nodejs-echo:
    lang: node
    handler: ./sample/nodejs-echo
    image: alexellis/faas-nodejs-echo:0.1
    annotations:
     date_created: "2017-12-31T23:59:60Z"
```
