### ISSUE TITLE
Suggestion: Configurable function directory name

### ISSUE THREAD

**Issue by dmcclory** [openfaas/faas-cli#481]
It would be nice if a user could specify the output directory for the function code when they are creating a new function.

## Expected Behaviour

I'm imagining there would be a new flag:

```
faas new name-with-hyphens --lang=python3 --function-dir=simplename
```

the resulting tree would be:
```
.
├── simplename
│   ├── __init__.py
│   ├── handler.py
│   └── requirements.txt
├── name-with-hyphens.yml
```

and the stack yaml file would be:

```
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  name-with-hyphens:
    lang: python3
    handler: ./simpledirname
    image: name-with-hyphens
```

## Current Behaviour

Right now, people need to make those changes manually.

## Possible Solution
It seems like it would require a few changes to `commands/new_function.go`

## Context
The only characters that are allowed in a function name are "a-z, 0-9 and dashes". I'm in an environment where I'd like be able to have function names that use those characters, but also guarantee that the output dir will be a valid python module name. I know that that is probably a very specific use case, but there may be other edge cases that this would handle.
