### ISSUE TITLE
Proposal: Support build-time labels for Docker images

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#567]
As a faas-cli user I would like to provide a series of labels to be built into my Docker images so that I can identify, catalog and organize my images. 

This feature was suggested by "zeeque" on Slack who works at e2x.com.

An example is http://label-schema.org/rc1/

## Expected Behaviour

```
faas-cli up  \
  --build-label build-date=org.label-schema.build-date="2016-04-12T23:20:50.52Z"
  --build-label vcs-url=org.label-schema.vcs-url="https://github.com/nginx/nginx"
```

We may also want to place these labels in YAML files such as:

```
  ruby-echo:
    lang: ruby
    handler: ./sample/ruby-echo
    image: alexellis/ruby-echo:0.2
    build_labels:
      - build-date=org.label-schema.build-date="2016-04-12T23:20:50.52Z"
      - vcs-url=org.label-schema.vcs-url="https://github.com/nginx/nginx"
```

There may be a place in the YAML schema where we can collate these new types of labels and the existing `build_options` overrides.

## Current Behaviour

These labels could only be added manually, not via the `faas-cli build / up` flow which may make our tooling less useful for those already adopting label schema and other build-time labels for their Docker images.

## Possible Solution

As suggested above.
