### ISSUE TITLE
Feature: Provider-specific extensions required

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#623]
## Expected Behaviour

In Kubernetes some users require the use of "tolerations" which allow a function to run on a server which is specifically tainted to stop functions running there. The use-case is things like a pool of ephemeral nodes.

See also:

- [taints & tolerations](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/)
- Affinity rules: [node/pod affinity and anti-affinity rules](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity).

## Current Behaviour

Users should avoid depending on taints, or patch PodSpec manually, or use a Kubernetes Mutating Controller to do this in an automated fashion

## Possible Solution

An extension to the stack.yml file which can be safely ignored by other providers:

```
kubectl taint nodes node1 key1=value1:NoSchedule
```

```yaml
functions:
  spot-function:
    image: spot:latest
    skip_build: true
    kubernetes_extensions:
      tolerations:
      - key: "key1"
         operator: "Equal"
         value: "value1"
         effect: "NoSchedule"
```

An approach may be to add a `kubernetes_extensions` element which is strongly typed and optional. This would also be reflected via `faas-cli generate` in the CRD YAML output.

Another approach may be to make this a blob of quoted text in YAML

```yaml
extensions:
  - name: kubernetes
     value: |
      tolerations:
      - key: "key1"
         operator: "Equal"
         value: "value1"
         effect: "NoSchedule"
```

## Steps to Reproduce (for bugs)

1. Create a Kubernetes cluster
2. Apply a taint to the node(s)
3. Try to schedule a function (it won't be able to)
4. Now add the toleration by editing the PodSpec and it will schedule

## Context

https://github.com/openfaas/faas/issues/1125

**Comment by alexellis** [comment]
Request for comment from @rgee0 @johnmccabe @stefanprodan @LucasRoesler 

This is something we have to find a solution for, so please try to make your participation constructive towards addressing the need of the users.

**Comment by alexellis** [comment]
@stefanprodan can you add the helm package you mentioned that can dynamically unmarshal a YAML section? https://github.com/stefanprodan/gitops-helm

**Comment by alexellis** [comment]
Suggestion via Ed:

Should annotations be used?

**Comment by LucasRoesler** [comment]
the new v3 of the yaml package was announced that adds some power and flexability and could allow use to parse 

```yaml
functions:
  spot-function:
    image: spot:latest
    skip_build: true
    kubernetes_extensions:
      tolerations:
      - key: "key1"
         operator: "Equal"
         value: "value1"
         effect: "NoSchedule"
```

```go
type Function struct {
    image  string
    kubernetes_extensions yaml.Node
}
```

During the last contributors chat, there was a suggestion that we could provide simplified limited support for certain use cases.  Was that further discussed? Do we want/need to support the entire  feature set of tolerations and affinity or will one or two simplified use cases cover 90% of users?

**Comment by alexellis** [comment]
@ibuildthecloud any thoughts?

**Comment by stefanprodan** [comment]
I vote for:

```yaml
functions:
  spot-function:
    image: spot:latest
    skip_build: true
    kubernetes_extensions:
      tolerations:
      - key: "key1"
         operator: "Equal"
         value: "value1"
         effect: "NoSchedule"
```

As Lucas said we can use `yaml.Node` (pkg: `gopkg.in/yaml.v3`)  or `chartutil.Values` (pkg: `k8s.io/helm/pkg/chartutil`) to avoid vendoring Kubernetes client-go in the CLI.
