### ISSUE TITLE
Feature: Version the schema

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#624]
## Expected Behaviour

The stack.yml file needs to be versioned so that we can make breaking changes in the future

## Current Behaviour

We are at an implicit version 1.0.0

## Possible Solution

Decide how we are going to add this and where before working on #623 

Example:

```yaml
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  mem-reader:
    lang: golang-middleware
    handler: ./mem-reader
    image: alexellis2/mem-reader:0.1.0
    limits:
      memory: 500Mi
    requests:
      memory: 500Mi
```

**Comment by alexellis** [comment]
Request for comment @stefanprodan @johnmccabe @LucasRoesler

**Comment by alexellis** [comment]
Docker Compose uses i.e. `version: 2.0`

**Comment by alexellis** [comment]
I.e.

```
version: 1.0.0
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  mem-reader:
    lang: golang-middleware
    handler: ./mem-reader
    image: alexellis2/mem-reader:0.1.0
    limits:
      memory: 500Mi
    requests:
      memory: 500Mi
```
