### ISSUE TITLE
Proposal: support multi-arch functions

### ISSUE THREAD

**Issue by aklyachkin** [openfaas/faas-cli#662]
## Current Behaviour
As for now if I want to have a function, which runs on amd64, and ppc64le, I have to do following:

* Create a new function

```
$ faas-cli new function --lang golang-http
```

* Change function.yml to have 2 functions for 2 architectures:

```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://gateway:31112
functions:
  testma-amd64:
    lang: golang-http
    handler: ./function
    image: id/function:latest-amd64
  testma-ppc64le:
    lang: golang-http-ppc64le
    handler: ./function
    image: id/function:latest-ppc64le
```

* Build 2 functions:

```
$ faas-cli build -f ./function.yml
```

* Push them to docker
* Create manifest

```
$ docker manifest create id/function:latest id/function:latest-amd64 id/function:latest-ppc64le
```

* Push manifest

```
$ docker manifest push id/function:latest
```

* deploy the function to Kubernetes???

## Expected Behaviour

Something like:

```
faas-cli up -f ./function.yml -a amd64,pcc64le
```

## Context
I just want to build functions on my mac, test them on mac and on intel, and deploy them into production anywhere.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.8.21
* Docker version ( Full output from: `docker version` ):
18.06.0-ce
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS, Linux
