### ISSUE TITLE
Save OAuth tokens to the OpenFaaS config file

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#663]
## Expected Behaviour

We should automatically save OAuth tokens to the OpenFaaS config file and read them from there if no `--token` parameter is passed for the various commands.

This needs to be backwards compatible with basic auth logins, so it will need some changes to the config file to support the new schema or extension.

## Current Behaviour

Following these instructions users can authenticate with Auth0 and retrieve a token on the console, which can then be used with the `--token` parameter.

https://docs.openfaas.com/reference/cron/#authentication

## Possible Solution

* Introduce a schema version to the config file
* Migrate older versions to newer ones. Minio does this and we could probably take some inspiration from the way they implemented it.
* Decide in the config file if each gateway URL is to use basic-auth or a Bearer token
* Based upon what credentials are stored, use the token instead of the basic auth credentials with the server-side commands.

## Context

This completes the work of https://github.com/openfaas/faas-cli/issues/647

**Comment by viveksyngh** [comment]
Derek assign: me

**Comment by viveksyngh** [comment]
Design Proposal. 

```go
type ConfigFile struct {
	AuthConfigs []AuthConfig `yaml:"auths"`
	FilePath    string       `yaml:"-"`
        Version     string       `yaml:"version"`
}

type AuthConfig struct {
	Gateway string `yaml:"gateway,omitempty"`
	Auth    string `yaml:"auth,omitempty"`
	Token   string `yaml:"token,omitempty"`
}

```
Before any sub commands are run, migrate config file from the initial version to the latest version and save it so that CLI will have updated version of the CLI. 

Migration will happen in sequential order from Initial Version like `Initial Version -> V1 -> V2 .. -> Final Version` so that each new version has to know how to migrate it version it's previous version. 

I think this is how minio also handles the migration.

**Comment by LucasRoesler** [comment]
@viveksyngh a map of AuthConfigs is probably going to be easier to use in the CLI, e.g. it will be easier to lookup and/or update an auth based on the gateway  _or_ we can then name the auth configs so that we could even allow multiple configs per Gateway and a user could then have one that is an "admin" scoped config and one "normal user" config for the same gateway. 

```go
type ConfigFile struct {
	AuthConfigs map[string]AuthConfig `yaml:"auths"`
	FilePath    string       `yaml:"-"`
        Version     string       `yaml:"version"`
}
```


What is the `Auth` field in the `AuthConfig`, auth type?

```go
type AuthConfig struct {
	Gateway string `yaml:"gateway,omitempty"`
	Auth    string `yaml:"auth,omitempty"`
	Token   string `yaml:"token,omitempty"`
}
```

**Comment by viveksyngh** [comment]
Yes Agree..  We can convert `AuthConfigs` to a Map which will be easy to manipulate.  

The second option will change the current flow and we will have include a auth name flag with each command to select an auth which will be used with that command. Do we have an ask or an use case to enable multiple auth for an gateway. 

 `Auth` filed is basically type of the authentication like `basic` or `bearer`.

**Comment by LucasRoesler** [comment]
I didn't mean to imply that we should build/allow multiple auths. Rather, just indicating that it would be possible and I could see a use case in the future, but it would require more though about UX before we decided to do it

**Comment by alexellis** [comment]
I think the reason we used the list over the map before was because Joe Beda strongly recommended against it. It was too late to change the function map in the `stack.yml`, but not too late to change to an array of key/value pairs in the login config that @stefanprodan wrote for us.

**Comment by LucasRoesler** [comment]
Is the reason to prefer a slice saved on an issue somewhere, would love to read it

**Comment by alexellis** [comment]
The YAML would look like:

```yaml
things:
  - name: thing_name_1
     value: value_of_thing_1
     other_property: prop_1
  - name: thing_name_2
     value: value_of_thing_2
     other_property: prop_2
```

vs:


```yaml
things:
     thing_name_1
       value: value_of_thing_1
       other_property: prop_1
     thing_name_2
       value: value_of_thing_2
       other_property: prop_2
```

**Comment by alexellis** [comment]
This is what we have today:

```yaml
auths:
- gateway: http://192.168.0.35:8080
  auth: basic
  token: etc==
- gateway: http://192.168.0.1:8080
  auth: basic
  token: yzx==
- gateway: http://192.168.0.101
  auth: basic
  token: aefs==
```

**Comment by viveksyngh** [comment]
Second one looks more clean. With Second one, we should be able to also store multiple auth per gateway as it is list. With `map` approach, to store multiple auth per gateway we will have to also have a nested map or list which will look more complex IMO. 

However, Minio stores using map for each host. 

```json
{
	"version": "9",
	"hosts": {
		"gcs": {
			"url": "https://storage.googleapis.com",
			"accessKey": "YOUR-ACCESS-KEY-HERE",
			"secretKey": "YOUR-SECRET-KEY-HERE",
			"api": "S3v2",
			"lookup": "dns"
		},
		"local": {
			"url": "http://localhost:9000",
			"accessKey": "",
			"secretKey": "",
			"api": "S3v4",
			"lookup": "auto"
		},
          }
 }
```

**Comment by LucasRoesler** [comment]
@viveksyngh if you have multiple auths per gateway, you will need a unique name on them anyway so that you know how to look them up,  so a map won't be an issue there.

I prefer the map because it is easier to use and interact with because you don't need to filter a slice to find the matching configuration. 

So far the discussion seems to be about the aesthetics of a yaml list versus a yaml map, is that really the reason to prefer one over the other?

**Comment by alexellis** [comment]
@viveksyngh 

We have this today:

```yaml
- gateway: http://127.0.0.1:8080
  auth: basic
  token: base64
```

Could we simply use the `auth` field and retain everything else?

```yaml

- gateway: http://127.0.0.1:8080
  auth: oauth2
  token: token-goes-here
```

What do you think? It also doesn't need any migration effort.
