### ISSUE TITLE
[Feature] Provide --build-args for functions in stack.yml

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-cli#687]
This was originally proposed in https://github.com/openfaas/faas-cli/issues/262 but was eventually implemented as flags on the `faas-cli`.  This CLI behavior is documented here https://docs.openfaas.com/cli/build/#30-pass-custom-build-arguments

To ensure reproducible and portable builds, we should support supplying build args via the YAML stack file.

## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

It should be possible for both of these commands to produce the same build

```sh
faas-cli build
faas-cli build --build-arg ARGNAME1=argvalue1
```

## Current Behaviour

The only way to set build args is via tha CLI

```sh
faas-cli build --build-arg ARGNAME1=argvalue1
```

## Possible Solution

Allow specifying a map of build args per function in the stack yaml, for example

```yaml
functions:
  url-ping:
    lang: python
    handler: ./sample/url-ping
    image: alexellis2/faas-urlping
    build_arg:
        cookies: "yup"
        pie: "please"
        brownies: "of_course"
```

**Comment by alexellis** [comment]
I would like to see if we can get it into `build_options`, even if we write a migrator like @viveksyngh started looking into for the OpenFaaS YAML config file.

Should this be a map or an array? I guess it's really a KV?

**Comment by cconger** [comment]
I'm a fan of distributing the build options down to the end function yaml as much as possible.  It's ideal if you have as much of the function definition close to the function and out of the template, which is a big benefit of having the additional packages wiring.  If we had build_args available in the `function.yml` file would there still be a benefit to having language level build flags (aside from backwards compatibility)?

**Comment by alexellis** [comment]
Good question. In a sense the packages are maintained i.e. dev and mysql are not 1:1 but map to curated packages.

**Comment by alexellis** [comment]
@rgee0 

https://github.com/openfaas/faas-cli/issues/687#issuecomment-528030679

That's correct

We now have a use-case where we want to enable Go modules (some of the time) and @bmcstdio made a `--build-arg` available for that. How do we move this forward?

Today `build_options` looks like this:

```
build_options:
- ca-certificates
```

Taken from https://docs.openfaas.com/reference/yaml/#function-build-options

I don't know how heavily it's being used, but we could use a schema version change and bump it to be richer.

```yaml
build_options:
  bundles:
   - ca-certs
  build_args:
    GO_MOD: 1
```

**Comment by chrisrichard** [comment]
If you can provide a bit of guidance on implementation we might be able to help with this one.

**Comment by LucasRoesler** [comment]
From how I understand the conversation, i think @alexellis  wants to introduce the following yaml structure

```yaml
version: 1

provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  url-ping:
    lang: python
    handler: ./sample/url-ping
    image: alexellis2/faas-urlping
    build_options:
      bundles:
      - ca-certs
      build_args:
        GO_MOD: 1
```
there are a couple important change in this structure

1. a `version` value.  This would allow us to introduce a breaking change in the function spec. We would need to freeze the current spec as `version: 0` and when version is missing we assume `0`.  Ideally we should be just parsing to a single internal structure, just using a different parser/loader based on the version in the file. That way the internal code only needs to deal with a single structure.
2. the `build_options` would change from a list to a map

     ```yaml
    build_options:
      bundles:
      - ca-certs
      build_args:
        GO_MOD: 1
    ```
    this change would allow us to expand the build time options to now include the `build_args` map. This map would be translated to the docker `--build-args` flags during the docker build.  This would need an update here https://github.com/openfaas/faas-cli/blob/0ab4012784510381e2b90c031ede3d77197b10b1/builder/build.go#L125-L135 and here https://github.com/openfaas/faas-cli/blob/0ab4012784510381e2b90c031ede3d77197b10b1/builder/build.go#L239-L276

    The CLI would need to be updated to read the build option packages from `build_options.bundles`.  See here in the source code https://github.com/openfaas/faas-cli/blob/0ab4012784510381e2b90c031ede3d77197b10b1/builder/build.go#L52
3. of course the docs would need to be updated as well https://docs.openfaas.com/reference/yaml/#function-build-options  we would need to decide how we want to document the version behavior. I am not sure if we want to follow the example of postgres and have entire copies of the documentation for each release _or_ just add a branch in that part of the documentation for the two different versions.


If we want to avoid a breaking change, then we need a new name for the `build_options`. Perhaps we can deprecate `build_options` over the next couple of months and replace it with `build_config` field?  Use the same structure described as above but then we need to worry less about the `version` field.

**Comment by alexellis** [comment]
I'm not seeing much usage in OSS repos: (if this search is working as expected) https://github.com/search?q=faas+build_options&type=Code

**Comment by alexellis** [comment]
I'm leaning towards build_config

**Comment by LucasRoesler** [comment]
I think i would rather introduce a breaking change or use `build_config` versus mixing the build options and flag parsing

**Comment by martindekov** [comment]
So should we stay with:
```
build_options:
- ca-certificates
- build-essential
```
And not mix config and flag parsing? Did you reach consensus?

**Comment by abhayvatoo** [comment]
From the above conversation, I think @alexellis and @LucasRoesler are good with deprecating `build_option` and replacing it with `build_config`. The new yaml structure will look like:
```
 version: 1

provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  url-ping:
    lang: python
    handler: ./sample/url-ping
    image: alexellis2/faas-urlping
    build_config: # build_options changed to build_config
      bundles: # would be passed as ADDITIONAL_PACKAGES
      - ca-certs
      build_args: # would be translated to the docker --build-args flags during the docker build
        GO_MOD: 1
```
@chrisrichard and I am working on this. I believe we understood the issue correctly. Please let us know otherwise or in case of any issue.
