### ISSUE TITLE
about create HPAv2 rule

### ISSUE THREAD

**Issue by haozibi** [openfaas/faas-cli#688]
Hello @alexellis , I want to ask some questions about HPAv2.

I have changed the auto-scaling to HPAv2 by https://docs.openfaas.com/tutorials/kubernetes-hpa/  and it works fine.

But there are some questions about creating the HPAv2 rule, can I add the HPAv2 rule using faas-cli or function yaml instead of kubectl. Because I have to deploy more functions, and I don't have permission to use kubectl

this is my function yaml

```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:9090
functions:
  hpa-002:
    lang: go
    handler: ./hpa-002
    image: hpa-002:latest
    requests:
      memory: 50Mi
      cpu: 200m
    limits:
      memory: 500Mi
      cpu: 3000m
    environment:
      write_debug: true
      read_timeout: 90s
      write_timeout: 90s
```

## Expected Behaviour

Add HPAv2 rule by faas-cli or function yaml

## Current Behaviour

Add HPAv2 rule by kubectl

```shell
kubectl autoscale deployment -n openfaas-fn \
  nodeinfo \
  --cpu-percent=50 \
  --min=1 \
  --max=10
```

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:
