### ISSUE TITLE
Is it possible to run pre/post build commands?

### ISSUE THREAD

**Issue by ghindle** [openfaas/faas-cli#690]
## Expected Behaviour
I have a node function which needs to be compiled via babel before the image can be built. At the moment I run the build script manually before running either `faas-cli build` or `faas-cli up`.

## Possible Solution
Add commands to predefined hooks per function via the stack.yml (example below). The working directory of the commands would be the root of the function's directory. Additional hooks could be added for different points of the lifecycle including but not restricted to build, push, deploy. 

`stack.yml`:
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  example:
    lang: node10-express
    handler: ./example
    image: example
    hooks:
      build:
        pre: npm run build
        post: npm run clean
```
