### ISSUE TITLE
Additional template configuration not used at build time

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#725]
Additional template configuration not used at build time

## Expected Behaviour

If `templates` are defined in `stack.yml`, then `faas-cli build` should pull the templates if the `templates` folder does not exist.

## Current Behaviour

I defined a template and source as above, but had to run `faas template pull stack` separately.

![Screenshot 2019-11-11 at 11 03 21](https://user-images.githubusercontent.com/6358735/68582844-9ffb0600-0473-11ea-82ee-00771ae71b8e.png)

```yaml
provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  system-dashboard:
    lang: node10-express
    handler: ./of-cloud-dashboard
    image: functions/of-cloud-dashboard:0.7.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
    environment_file:
      - dashboard_config.yml

configuration:
  templates:
    - name: node10-express
      source: https://github.com/openfaas-incubator/node10-express-template
```

## Possible Solution

In the same way that we pull from the default templates repo, we should combine any additional repos and use them too.

## CLI version

Latest release as of today.
