### ISSUE TITLE
faas-cli deploy adds "docker.io/" to container image of private container registry

### ISSUE THREAD

**Issue by KaiWedekind** [openfaas/faas-cli#760]
## Expected Behaviour

I'm using GitLab CI to build, push and deploy faas function.

Deploy openfaas functions with `faas-cli deploy` without adding  **docker.io/** to the private docker repositories address 

**.gitlab-ci.yml**
```
stages:
  - build

# Cache the templates and build-context to speed things up
cache:
  key: ${CI_COMMIT_REF_SLUG} # i.e. master
  paths:
  - ./faas-cli
  - ./template

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.1-dind

before_script:
  - docker info
  # Login & Push Docker image to private repo
  - echo -n "$CI_DOCKER_LOGIN" | docker login --username admin --password-stdin registry.<HOST>.io

# Build the whole stack using only the faas-cli
docker-build:
  stage: build
  image: docker:19.03.1

  script:
    - apk add --no-cache git
    - if [ -f "./faas-cli" ] ; then cp ./faas-cli /usr/local/bin/faas-cli || 0 ; fi
    - if [ ! -f "/usr/local/bin/faas-cli" ] ; then apk add --no-cache curl git && curl -sSL cli.openfaas.com | sh && chmod +x /usr/local/bin/faas-cli && /usr/local/bin/faas-cli template pull && cp /usr/local/bin/faas-cli ./faas-cli ; fi

    # Build Docker image
    - /usr/local/bin/faas-cli build --tag=sha --parallel=2

    - /usr/local/bin/faas-cli push --tag=sha
    - echo -n "$CI_OPENFAAS_PASSWORD" | /usr/local/bin/faas-cli login --username admin --password-stdin
    - faas-cli list

    # Deploy function from private repo
    - echo $OPENFAAS_PREFIX
    - /usr/local/bin/faas-cli deploy --tag=sha --send-registry-auth

  after_script:
    - docker logout registry.<HOST>.io

  only:
    - master

```

**stack.yml**

```
version: 1.0
provider:
  name: openfaas
  gateway: https://faas.<HOST>.io
functions:
  greet:
    lang: go
    handler: ./src
    image: registry.<HOST>.io/<GITLAB-GROUP>/go-functions
```

## Current Behaviour

Build and push works like charm, but `faas-cli deploy` adds **docker.io/** in front of the private container image address which lets my pipeline fail.

**Pipeline Error Message**
```
$ /usr/local/bin/faas-cli deploy --tag=sha --send-registry-auth
356 Deploying: greet.
357 Unexpected status: 400, message: unable to pull image docker.io/registry.<HOST>.io/<GITLAB-GROUP>/go-functions:latest-cb0a3ac: cannot pull: failed to resolve reference "docker.io/registry.<HOST>.io/<GITLAB-GROUP>/go-functions:latest-cb0a3ac": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
358 Function 'greet' failed to deploy with status code: 400

```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

```
CLI:
 commit:  30b7cec9634c708679cf5b4d2884cf597b431401
 version: 0.11.7

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.18.8
 sha:     76e463a7a017f81ed88ae7824d2ef7a3f60ed45e
 commit:  Always apply the function prefix trim for async functions


Provider
 name:          faas-containerd
 orchestration: containerd
 version:       0.6.1 
 sha:           c133b9c4ab883aa01a9521e6dee4279e215c0acb
```

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
* Link to your project or a code example to reproduce issue:
