### ISSUE TITLE
Feature request: sorted output from "faas-cli generate" command

### ISSUE THREAD

**Issue by brandonkal** [openfaas/faas-cli#777]
The output of `faas-cli generate --envsubst=false` is not deterministic.
It appears to choose a document order at random. This makes git diffs essentially useless on the output.

## Expected Behaviour
When I run the command with the same inputs, the output should be unchanged.

## Current Behaviour

The output is not sorted.

## Steps to Reproduce (for bugs)

1. Run on any YAML, for example [this folder](https://github.com/openfaas/openfaas-cloud/tree/master/yaml)
2. Run it again, and observe a different output.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.12.0

* Operating System and version (e.g. Linux, Windows, MacOS): Linux

**Comment by Amalkh5** [comment]
@brandonkal I am trying to reproduce it but when I run it with the same input I get the same output each time.

what I tried is the following:-
```
$ faas-cli new --lang go fn1
$ faas-cli generate --envsubst=false  --yaml fn1.yml
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: fn1
spec:
  name: fn1
  image: fn1:latest

$ faas-cli generate --envsubst=false  --yaml fn1.yml
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: fn1
spec:
  name: fn1
  image: fn1:latest
```

**Comment by brandonkal** [comment]
@Amalkh5 You need more than one YAML document (aka function). The issue is that generate changes the order of the documents at random.

**Comment by alexellis** [comment]
Perhaps providing a full example would be helpful @brandonkal?

**Comment by alexellis** [comment]
I believe what you're seeing is due to the fact that maps are not ordered in Golang. 

How are you using/running `generate`? Can you provide a little more context?

**Comment by brandonkal** [comment]
@alexellis if you want an example, here is one: 
https://github.com/openfaas/openfaas-cloud/blob/master/stack.yml

As I say it doesn't really matter what the input is, the output is always different if more than one function is involved.

Convert the map to a list of YAML documents and sort it alphabetically by `${metadata.namespace}-{metadata.name}` before writing to stdout.

**Comment by alexellis** [comment]
You could provide a simple example in the comments, I don't think it would take you very long, and can't understand why you won't?

**Comment by alexellis** [comment]
```
faas-cli new --lang python3 fn2 --append stack.yml
faas-cli new --lang python3 fn2 --append fn1.yml 
```

On each generation I saw the exact same ordering:

```
space-mini:issue alex$ faas-cli generate -f fn1.yml 
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: fn1
spec:
  name: fn1
  image: fn1:latest
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: fn2
spec:
  name: fn2
  image: fn2:latest

space-mini:issue alex$ faas-cli generate -f fn1.yml 
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: fn1
spec:
  name: fn1
  image: fn1:latest
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: fn2
spec:
  name: fn2
  image: fn2:latest

space-mini:issue alex$ faas-cli generate -f fn1.yml 
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: fn1
spec:
  name: fn1
  image: fn1:latest
---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: fn2
spec:
  name: fn2
  image: fn2:latest
```
