### ISSUE TITLE
Unexpected status: 500, message: Function.openfaas.com "<SOME_FUNCTION>" is invalid

### ISSUE THREAD

**Issue by joelcorporan** [openfaas/faas-cli#780]
I'm following a the tutorial for running OpenFaaS on AWS (https://aws.amazon.com/blogs/opensource/deploy-openfaas-aws-eks/) and deploying the function on that tutorial. However, I'm having issues deploying a function. I'd get a 500 message.

## Expected Behaviour
```
faas-cli up -f hello-python.yml
```
200 Status

## Current Behaviour
```
faas-cli up -f hello-python.yml
```
```
Deploying: hello-python.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Unexpected status: 500, message: Function.openfaas.com "hello-python" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"openfaas.com/v1", "kind":"Function", "metadata":map[string]interface {}{"creationTimestamp":"2020-03-16T17:22:09Z", "generation":1, "name":"hello-python", "namespace":"openfaas-fn", "uid":"aa8bf881-67aa-11ea-b165-16d96eae1e15"}, "spec":map[string]interface {}{"annotations":map[string]interface {}{}, "constraints":interface {}(nil), "environment":map[string]interface {}{}, "handler":"python index.py", "image":"corporan/hello-python:latest", "labels":map[string]interface {}{}, "limits":interface {}(nil), "name":"hello-python", "readOnlyRootFilesystem":false, "requests":interface {}(nil), "secrets":[]interface {}{}}}: validation failure list:
spec.constraints in body must be of type array: "null"

Function 'hello-python' failed to deploy with status code: 500
```
## Your Environment

* FaaS-CLI version 0.11.8
* Docker version 19.03.8
* Kubernetes (FaaS-netes)
* MacOS 10.14.6

**Comment by alexellis** [comment]
You'll need to share hello-python.yml

**Comment by alexellis** [comment]
This is usually a whitespace thing cc @stefanprodan @LucasRoesler

**Comment by joelcorporan** [comment]
handler.py

```
def handle(req):
    """handle a request to the function
    Args:
        req (str): request body
    """

    return req
```

hello-python.py

```
version: 1.0
provider:
  name: openfaas
  gateway: http://xxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxx.us-east-1.elb.amazonaws.com:8080
functions:
  hello-python:
    lang: python
    handler: ./hello-python
    image: corporan/hello-python:latest
```
