### ISSUE TITLE
Question on deleting functions from multiple-namespaces

### ISSUE THREAD

**Issue by zadigus** [openfaas/faas-cli#811]
I have the following `faas-stack.yml`:
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: ${OPENFAAS_GATEWAY_URL:-http://localhost:31112}
functions:
  login:
    namespace: ${OPENFAAS_NAMESPACE:-dev-fn}
    lang: dockerfile
    handler: ./backend/functions/Login
    image: shopozor/login-fn
```
I can up the stack like this:
```bash
faas-cli up -f faas-stack.yml
```
That works, though I've been struggling a lot trying to make it work.  Indeed, I get the following confirmation:
```
Deployed. 202 Accepted.
URL: http://localhost:31112/function/login.dev-fn
```
Now, my issue is that the following command does not remove the functions declared in my stack:
```bash
faas-cli remove -f faas-stack.yml
```
Even though I get the confirmation
```
Deleting: login.
```
the function is actually not removed. Instead, I need to call
```bash
faas-cli remove login -g ${OPENFAAS_GATEWAY_URL} -n dev-fn
```
Then I get the confirmation
```
Deleting: login.
Removing old function.
```
and the function is really removed. From that behavior, I understand the `namespace` value in the `faas-stack.yml` is ignored in the `remove` command, which is surprising.

## Expected Behaviour
The command
```bash
faas-cli remove -f faas-stack.yml
```
should provide the same result as the command
```bash
faas-cli remove login -g ${OPENFAAS_GATEWAY_URL} -n dev-fn
```
in that simple case where I only have one function. Of course, with more functions, the former command should successfully remove all the functions from the namespace specified in the yaml file.

## Current Behaviour
The command
```bash
faas-cli remove -f faas-stack.yml
```
has no effect in the specified namespace.

## Possible Solution
Currently, my work-around is to manually remove all the functions from the stack with commands like:
```bash
faas-cli remove login -g ${OPENFAAS_GATEWAY_URL} -n dev-fn
```
Of course, that's annoying, because I have a stack file with my whole defined there! I don't want to type one line of code for each function I have in my stack. I'd rather like to use the stack, which works for deployment.

## Steps to Reproduce (for bugs)

1. Create a simple stack
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: ${OPENFAAS_GATEWAY_URL:-http://localhost:31112}
functions:
  login:
    namespace: ${OPENFAAS_NAMESPACE:-dev-fn}
    lang: dockerfile
    handler: ./backend/functions/Login
    image: shopozor/login-fn
```
2. Up the stack
```bash
faas-cli up -f faas-stack.yml
```
See that your functions are up.
3. Remove the stack
```bash
faas-cli remove -f faas-stack.yml
```
See that your functions are still up and never vanish from your function namespace.

## Context
I'm pretty new to openfaas. I started using it this week. I am trying to deploy my .Net Core functions to my k8s cluster in the simplest possible way. I have already a pretty big stack of helm charts to deploy, together with functions that I am currently developping for my e-commerce platform.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
CLI:
 commit:  f7c29ea19b5df9d7aa87e9c70aacf4d9315da2cd
 version: 0.12.4
```
* Docker version ( Full output from: `docker version` ):
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
I am using kubernetes on Docker for Desktop under Windows:
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):
Windows

* Link to your project or a code example to reproduce issue:
You don't need anything special. Just create a new function from some template and you should be able to reproduce this.
