### ISSUE TITLE
Support request for faas-cli docker image

### ISSUE THREAD

**Issue by joshuasprow** [openfaas/faas-cli#818]
I have a function deployed to OpenFaas on a Rancher Kubernetes cluster and started seeing cron jobs fail when using image 0.12.6 and later.  I'm using basically the same yaml from [the docs](https://docs.openfaas.com/reference/cron/) and haven't changed my function code, so `faas-cli` is the most likely culprit.

## Expected Behaviour
The cron workload triggers the OpenFaas function, as expected.

## Current Behaviour
When the job fails, it emits an error: `Unknown command "/bin/sh" for "faas-cli"` from the cron workload. Also, the function itself is not triggered.

## Possible Solution
Lock the faas-cli version to 0.12.4. It's probably a good idea to lock the version regardless, right? I'm pretty new to Kubernetes, so I could use a hand.

## Steps to Reproduce (for bugs)
1. Deploy the function to OpenFaas. Here's a semi-redacted version of my stack.yml:
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  function:
    lang: node12
    handler: ./function
    image: {{ image-url }}
    annotations:
      topic: cron-function
      schedule: "*/30 * * * *"
    environment:
      exec_timeout: 120s
      read_timeout: 120s
      upstream_timeout: 120s
      write_timeout: 120s
      write_debug: true
    secrets:
      - function-secrets
```
2. Apply a manifest to create the cron workload:
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: function
  namespace: openfaas
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: openfaas-cli
              image: openfaas/faas-cli:0.12.6
              args:
                - /bin/sh
                - -c
                - echo "verbose" | faas-cli invoke function -g http://gateway.openfaas:8080
          restartPolicy: OnFailure
```
3. Check cron workload logs for error.

## Context
Just trying to schedule my OpenFaas functions.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):
`0.12.6`
I'd give the full output but the container crashes before I can `exec` into it.

* Docker version ( Full output from: `docker version` ): 
`18.9.2`

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)? 
`Kubernetes`

* Operating System and version (e.g. Linux, Windows, MacOS):
`Linux`

* Link to your project or a code example to reproduce issue:
I'm not sure what code would be relevant other than the yaml above. I'd be happy to provide any other info if someone asks for something specific.

**Comment by alexellis** [comment]
We changed the image so that the CLI itself is the entry point. That's probably why. Cc @utsavanand2 @LucasRoesler

**Comment by alexellis** [comment]
/set title: Support request for faas-cli docker image

**Comment by utsavanand2** [comment]
Hii @joshuasprow !
You might want to make some changes to your CronJob by adding a `command` field with value `["/bin/sh", "-c"]` and hence remove `/bin/sh` and `-c` from the `args`. 
The final YAML of your CronJob should look something like this.

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: function
  namespace: openfaas
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: openfaas-cli
              image: openfaas/faas-cli:0.12.6
              command: ["/bin/sh", "-c"]
              args:
                - echo "verbose" | faas-cli invoke function -g http://gateway.openfaas:8080
          restartPolicy: OnFailure
```

Let us know if it works out for you!
