### ISSUE TITLE
faas-cli generate is not including annotations for OpenFaaS CRs

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#890]
## Expected Behaviour

```
faas-cli generate
```

with this text:

```
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
 url-ping:
   lang: python
   handler: ./sample/url-ping
   image: alexellis/faas-url-ping:0.2
   annotations:
     com.scale.zero: 1
```

Should output:

```
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: url-ping
spec:
  name: url-ping
  image: alexellis/faas-url-ping:0.2
  environment:
    debug: "true"
  labels:
    com.openfaas: "1"
  annotations:
    test: "true"
```

## Current Behaviour

Annotations are missing and not present in the unit tests either.

## List All Possible Solutions and Workarounds

Add code to populate and test the annotations are present.

## Context

Reported by someone who uses the cron-connector and wanted to deploy via kubectl with annotations.
