### ISSUE TITLE
Add namespace to generated functions

### ISSUE THREAD

**Issue by goncalo-oliveira** [openfaas/faas-cli#892]
Running the generate command is not adding the function(s) namespace.

## Expected Behaviour
The following command

```
faas-cli generate \
  --from-store nodeinfo \
  > nodeinfo-store.yaml
```

Should give this

```
---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: nodeinfo
  namespace: openfaas-fn
spec:
  name: nodeinfo
  image: ghcr.io/openfaas/nodeinfo:latest
  labels: {}
```

Notice the namespace.

## Current Behaviour
The namespace is not added, instead it gives this

```
---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: nodeinfo
spec:
  name: nodeinfo
  image: ghcr.io/openfaas/nodeinfo:latest
  labels: {}
  annotations: {}

```

## Are you a GitHub Sponsor (Yes/No?)
Yes

Check at: https://github.com/sponsors/openfaas
- [x] Yes
- [ ] No

## List All Possible Solutions and Workarounds
The current workaround is to manually add the namespace to the generated file, or if using inline with kubectl, passing the flag `--namespace=openfaas=fn`.

## Which Solution Do You Recommend?
If the namespace is not provided in the function spec, it should use the default - openfaas-fn. If the function spec specifies a particular namespace, it should use that one.

## Steps to Reproduce (for bugs)
Taken from [here](https://www.openfaas.com/blog/manage-functions-with-kubectl/).
```
faas-cli generate \
  --from-store nodeinfo \
  > nodeinfo-store.yaml
```

## Context
Attempting to deploy to a cluster without access to the gateway.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

CLI:
 commit:  77ad215bcc6291dbf72c73caffe4d76aa2bb6fb1
 version: 0.13.11
Handling connection for 8080

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.20.12
 sha:     a6dbb4cd0285f6dbc0bc3f43f72ceacdbdf6f227

Provider
 name:          openfaas-operator
 orchestration: kubernetes
 version:       0.13.2 
 sha:           6caf24ba21f7af171e2ade40daa033b05584b695

* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
FaaS-netes

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:
