### ISSUE TITLE
Specify an environment file to faas-cli deploy

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-cli#907]
## Expected Behaviour

When a user of openfaas has two or more environments, and environment variables that are specific to each such as

Testing

```yaml
environment:
    db_host: "postgresql.svc.local"
    db_port: "5432"
    db_name: "defaultdb"
    db_ssl_mode: "disable"
```

Staging

```yaml
environment:
    db_host: "todo-pg11-do-user-2197152-0.b.db.ondigitalocean.com"
    db_port: "25060"
    db_name: "defaultdb"
    db_ssl_mode: "require"
```

They should have a mechanism to specify one set of environment variables or another.

## Current Behaviour

Today we have the ability to add `environment_file` to the stack.yml, but it can only contain a static list, which cannot be switched easily.

```yaml
    environment_file:
     - staging.yaml
#     - prod.yaml
```

Where the corresponding files contain the data required.

## List All Possible Solutions and Workarounds

A workaround could be to [use the env-var substitution support](https://docs.openfaas.com/reference/yaml/#yaml-environment-variable-substitution):

```yaml
    environment_file:
     - ${$OPENFAAS_ENV:-staging}.yaml
```

Then run: 

```bash
# Picks "prod.yaml"
OPENFAAS_ENV=prod faas-cli deploy

# Picks "staging.yaml"
OPENFAAS_ENV=prod faas-cli deploy
```

## Which Solution Do You Recommend?

Either the work-around or adding a new flag to `faas-cli deploy` of `--environment-file`

## Context

I've seen various commercial users get confused here and end up building esoteric and complex tooling to apply overrides to their configuration files.

I also ran into this whilst working on the OpenFaaS add-on for Everyday Golang.
