### ISSUE TITLE
Read-only root filesystem settings is lost when using `faas-cli generate`

### ISSUE THREAD

**Issue by welteki** [openfaas/faas-cli#928]
The read-only root filesystem configuration from the stack.yml is not included in CRDs generated with `faas-cli generate`

## Expected Behaviour

When `readonly_root_filesystem` is set in the stack.yml configuration of a function it should also be included in the spec of the CRD generated with `faas-cli generate`

stack.yml:
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080/
functions:
  python3-http-fn:
    lang: python3-http
    handler: ./python3-http-fn
    image: welteki2/python3-http-fn:latest
    readonly_root_filesystem: true
```

CRD:
```yaml
---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: python3-http-fn
  namespace: openfaas-fn
spec:
  name: python3-http-fn
  image: welteki2/python3-http-fn:latest
  readOnlyRootFilesystem: true
```

## Current Behaviour

The `readonly_root_filesystem` setting in a stack.yml configuration is not included in the CRD after running `faas-cli generate`.

stack.yml:
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080/
functions:
  python3-http-fn:
    lang: python3-http
    handler: ./python3-http-fn
    image: welteki2/python3-http-fn:latest
    readonly_root_filesystem: true
```

CRD:
```yaml
---
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: python3-http-fn
  namespace: openfaas-fn
spec:
  name: python3-http-fn
  image: welteki2/python3-http-fn:latest
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Steps to Reproduce (for bugs)

1. Create a stack.yml file
```yaml
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080/
functions:
  python3-http-fn:
    lang: python3-http
    handler: ./python3-http-fn
    image: welteki2/python3-http-fn:latest
    readonly_root_filesystem: true
```
3. Run `faas-cli generate -f stack.yml`

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  fcf50cef7b3510d93dd109606fb300705bb509f2
 version: 0.14.6

Gateway
 uri:     http://gateway.cromulon.local:8000
 version: 0.2.0
 sha:     1676b1135f10e1487d037ef7b0c7a2783fdace8e


Provider
 name:          openfaas-operator
 orchestration: kubernetes
 version:       0.1.6 
 sha:           532dc025e52444f625e32b38ac49578cf305cbeb
```
* Docker version ( Full output from: `docker version` ):

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:
