### ISSUE TITLE
Question: How do I publish images when buildkit requires a self-signed certificate?

### ISSUE THREAD

**Issue by Altair-Bueno** [openfaas/faas-cli#954]
Add an option to configure the builder for `faas publish` 

## Expected Behaviour

A way to provide buildkit configuration options

## Current Behaviour

See https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md for buildkitd.toml configuration options

## Why do you need this?

I have a self signed CA certificate that buildkit needs to push the image to a local registry

## Who is this for?

Anybody deploying OpenFaaS on ARM using local infrastructure (Docker registry, mirrors, debug, ...)

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?

University of Málaga

## Are you a GitHub Sponsor

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [X] No

## List All Possible Solutions and Workarounds

No workarounds found

## Which Solution Do You Recommend?

A `--config` option like what standard buildkit offers

## Context

Unable to deploy OpenFaaS on my RPI cluster

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.15.8

* Docker version ( Full output from: `docker version` ):

```yaml
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.41 (downgraded from 1.42)
 Go version:        go1.19.5
 Git commit:        a5ee5b1dfc
 Built:             Thu Feb  9 19:15:59 2023
 OS/Arch:           darwin/amd64
 Context:           colima

Server:
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974ae9e6c219862907efdd76ec2e77ec930b
  Built:            Wed Oct 19 02:58:31 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        5fd4c4d144137e991c4acebb2146ab1483a97925
 docker-init:
  Version:          0.19.0
  GitCommit:
```

* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)? FaaS-netes, K3s

* Operating System and version (e.g. Linux, Windows, MacOS): macOS

* Link to your project or a code example to reproduce issue: Irrelevant
