### ISSUE TITLE
Question: generating image tags from Git

### ISSUE THREAD

**Issue by sebastianricaldoni** [openfaas/faas-cli#955]
## Expected Behaviour
I'm expecting to run `faas-cli deploy` to successfully deploy my function (pods, replicaset, etc)

## Current Behaviour
My pod is not deployed and instead I get the following error
```
Failed to apply default image tag "myRepo/myService:latest-fatal: detected dubious ownership in repository at '/github/workspace'\nTo add an exception for this directory, call:\n\n\tgit config --global --add safe.directory /github/workspace": couldn't parse image reference "myRepo/myService:latest-fatal: detected dubious ownership in repository at '/github/workspace'\nTo add an exception for this directory, call:\n\n\tgit config --global --add safe.directory /github/workspace": invalid reference format
```

## Why do you need this?
I need to be able to deploy newer versions of my functions. Something to note is that this all started happening a few days ago after `faas-cli` docker image was removed from Docker Hub and we started pulling the image from ghcr.io instead.
It seems that, for some reason, the commit SHA is not properly determined or read and ends up rendering something as `-fatal` instead of `-<COMMIT-SHA>`

## Who is this for?

What company is this for? Are you listed in the [ADOPTERS.md](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) file?
I'm using this with my customers.
And no, I don't seem to be listed in the adopters.md file

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds

I'm not sure yet 🤷‍♂️ 

## Which Solution Do You Recommend?

Honestly I've been using `faas-cli` without an issue. I'm definitely not an expert user. I have never committed any code  to the project. I'm only using the "basic" out-of-the-box commands `login` , `build`, `deploy`

## Steps to Reproduce (for bugs)
I'm using `faas-cli` inside a Github Action but not sure it is really a bug on `faas-cli`.
```
name: CI/CD on staging

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  func-build:
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: './src'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Define ENV VARS
        id: define_env
        run:  echo "::set-output name=github-sha-short::$(echo $GITHUB_SHA | cut -c 1-7)"

      - name: Install dependencies
        run: npm install
          
      - name: Pull template
        uses: actions/checkout@v2
        with:
          repository: 'openfaas/templates'
          path: 'repo-templates'
          token: ${{ secrets.ACTIONS_CI_CD_ACCESS_TOKEN }}
          ref: 'main'

      - run: |
          cp -r ../repo-templates/template ../template
          rm -rf ../repo-templates

      - name: Run shrinkwrap build
        uses: docker://ghcr.io/openfaas/faas-cli:latest-root
        with:
          args: build -f my-function.yml --build-arg --shrinkwrap

      - name: Login to OpenFaaS Gateway
        uses: docker://ghcr.io/openfaas/faas-cli:latest-root
        with:
          args: login -p ${{ secrets.OPENFAAS_GATEWAY_PASSWD }} \
                      -g ${{ secrets.OPENFAAS_GATEWAY_URL }}

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push the OpenFaaS function
        uses: docker/build-push-action@v2
        with:
          context: ./build/my-function/
          file: ./build/my-function/Dockerfile
          push: true
          tags: my/services-bulk-import-learners-api:latest-${{ steps.define_env.outputs.github-sha-short }}
          build-args: |
            NPM_AUTH_TOKEN=${{ secrets.NPM_CI_CD_ACCESS_TOKEN }}
            
      - name: Deploy the function
        uses: docker://ghcr.io/openfaas/faas-cli:latest-root
        with:
          args: deploy -f my-function.yml --tag sha --gateway ${{ secrets.OPENFAAS_GATEWAY_PROD }}
```

## Your Environment

I'm using this within Github Actions using `ubuntu-latest` ([see here](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md))
* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.16.1
* Docker version ( Full output from: `docker version` ):
`docker://20.10.13`
* Are you using Docker Swarm (FaaS-swarm ) or Kubernetes (FaaS-netes)?
No
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:
